task04をアップロードしました！
kawashima26/kintone_Dojo pull request #4
Opened 2023-06-20 00:22 UTC by kawashima26

お疲れ様です。いつもありがとうございます。

task04の成果物をアップロードしました。
task4-1は55行目から、task4-2は71行目からが、自分で書いたコードです。

お忙しいところ恐縮ですが何卒よろしくお願いします！

2023-06-21 05:12 UTC, poemypoemy8 commented
@kawashima26 
お疲れさまです！ レビューさせていただきましたので
ご確認お願いします。

2023-06-22 00:44 UTC, kawashima26 commented
@poemypoemy8 
レビューしていただきありがとうございます！

コードに関して修正点は特になしという形で大丈夫でしょうか…？🙏（レビューのコメントを見逃していたら申し訳ありません）

（task4-1,4-2のコードについても、マージする際は、task03同様、確認用のconsole.logやコメントアウトは削除してからにしようと思っております！）

2023-06-22 02:20 UTC, poemypoemy8 commented on task04/task4-1.html
> +  console.log(checkArray); // 確認用
デバッグ用消しておいてください！

2023-06-22 02:20 UTC, poemypoemy8 commented on task04/task4-1.html
> +
` let optionTotal1 = 0; // セキュアオプション総額の初期値は0
  let optionTotal2 = 0; // ディスク増設オプション総額の初期値は0`

変数分けてあるのですが、一つにまとめて計算できそうですね！
変数の初期化をするタイミングと、計算の演算子に気を付けてもう一度考えてみてください。
わかりそうになければコメントください！🙏

2023-06-22 02:20 UTC, poemypoemy8 commented on task04/task4-2.html
> +
配列を都度変数指定していると大変だと思うので、
特に実施しなくても問題ないですよ！

2023-06-22 02:20 UTC, poemypoemy8 commented on task04/task4-2.html
> +
`document.getElementById('price').textContent = 3900 + optionTotal1 + optionTotal2;`

ここで 3900をそのまま数値指定している状態なので、
右辺を変数1つだけでどうにかできないか？考えてみてください！

難しければ悩み過ぎない段階でコメントください👍

2023-06-22 02:21 UTC, poemypoemy8 commented
@kawashima26 
あ！ごめんなさい＞＜
githubを理解できてなかった…(;´･ω･) 今レビューのコメント見えるでしょうか？
確認お願いします🙏

2023-06-22 02:30 UTC, poemypoemy8 commented on task04/task4-2.html
> +
今回はこのままで問題ないです👱‍♂️

2023-06-23 00:03 UTC, kawashima26 commented
@poemypoemy8 
レビューしていただきありがとうございます！
レビューのメッセージ見えております🙇‍♀️

コード修正が完了しましたらまたご連絡いたします。
どうぞよろしくお願いいたします！

2023-06-23 01:06 UTC, kawashima26 commented on task04/task4-1.html
> +  console.log(checkArray); // 確認用
レビューを受けてこちらのconsole.logを削除しました！

2023-06-23 01:07 UTC, kawashima26 commented on task04/task4-1.html
> +
レビューを受けて変数を一つにまとめました！🙇‍♀️

2023-06-23 01:18 UTC, kawashima26 commented on task04/task4-2.html
> +
ありがとうございます！
こちらのレビューを受けて「右辺を変数1つだけ」にする方法を試行錯誤してみたのですが、まだ思いつかない状態です。ヒントなどいただいてもよろしいでしょうか…？🙇‍♀️

変更点と自分の考えたことを以下に記載しました。
【変更点】
- optionTotal1,optionTotal2を一つの変数（＝optionTotal）にまとめた
- `const monthprice = Number(document.getElementById('price').textContent);`で、3900を数値として変数monthpriceに定義した

【考えたこと】
`monthprice += optionTotal`にすることで、3900円にオプション額を足す式を作れないか、と考えたのですが、このコードを実行するとWebページ上で合計金額が変更されなくなってしまうため断念していました。（コンソールにエラーは出ていない状態でした。）

すみません、説明が上手くできているか不安なので、分かりづらい箇所がありましたらおっしゃってください…！
よろしくお願いいたします。

2023-06-23 01:19 UTC, kawashima26 commented
@poemypoemy8 
お疲れ様です。
レビューを受けてコードを修正いたしました！
お忙しいところ恐縮ですが、ご助言お願いいたします🙇‍♀️

2023-06-26 00:32 UTC, poemypoemy8 commented on task04/task4-1.html
> +
OKです！
前回のレビューの意図だった、
`optionTotal -= Number(chk0.value);` も反映されていました。

以下、マージする前の修正点と、確認だけいただきたい点を記載します。
■修正点
・デバッグ用の `console.log`を削除しておいてください

■確認だけしてほしいこと（修正しなくても問題ないです👌）
・ 現在の記述の仕方であれば、`monthprice` は getElementせず 「3900」で問題なさそうです
・初期金額・オプション金額で分けずチェックボックスのイベント外で
`let total = 3900` としておき、
チェックボックスのイベント内で
`document.getElementById('price').textContent = total;` とすれば右辺が変数ひとつになりそうですね！（）

以上です。
修正点で依頼した部分のみ対応してマージをお願いします！
お疲れさまでしたm(_ _)m

2023-06-26 00:34 UTC, poemypoemy8 commented on task04/task4-1.html
> +
OKです！
前回のレビューの意図だった、
optionTotal -= Number(chk0.value); も反映されていました。

2023-06-26 00:47 UTC, poemypoemy8 commented on task04/task4-2.html
> +
OKです！

現状はそれぞれオプションにチェックが入っていなかった場合の初期値を 0としてそれぞれのオプションを定義していると思います。

右辺の変数を1つにするには、オプションの初期値を定義するのではなく、
ボタンがクリックされたときに
表示されている金額を3900で定義し、
その状態でチェックボックスが押されたら追加していくという考え方をすればよさそうです。

つまり「オプションプランの初期値」を考えるのではなく、トータル金額の初期値を考えてみる ということになりそうです。

例えばボタンが押されたときに、
トータル金額を `let total = 3900;`
で定義した場合、どのようになるでしょうか？

2023-06-26 00:49 UTC, poemypoemy8 requested changes

2023-06-26 00:49 UTC, poemypoemy8 commented on task04/task4-2.html
> +
Kです！

現状はそれぞれオプションにチェックが入っていなかった場合の初期値を 0としてそれぞれのオプションを定義していると思います。

右辺の変数を1つにするには、オプションの初期値を定義するのではなく、
ボタンがクリックされたときに
表示されている金額を3900で定義し、
その状態でチェックボックスが押されたら追加していくという考え方をすればよさそうです。

つまり「オプションプランの初期値」を考えるのではなく、トータル金額の初期値を考えてみる ということになりそうです。

例えばボタンが押されたときに、
トータル金額を let total = 3900;
で定義した場合、どのようになるでしょうか？

2023-06-26 03:35 UTC, kawashima26 commented
@poemypoemy8 
レビューいただきありがとうございます！
> つまり「オプションプランの初期値」を考えるのではなく、トータル金額の初期値を考えてみる ということになりそうです。

なるほど…！ここに思い至りませんでした…！ありがとうございます！
レビューをもとに変更させていただきました。

何度もお手を煩わせて申し訳ありませんが、ご確認よろしくお願い致します🙇‍♀️💦

2023-06-27 09:06 UTC, poemypoemy8 approved these changes
OKです！

色々と試行錯誤いただいたかと思いますが、
修正お疲れさまでした！

2023-06-27 09:08 UTC, poemypoemy8 commented
@kawashima26 
修正おつかれさまでした！

確認してほしかった場所がばっちり直っているのでOKです👌
変数が少ないとすっきりとしてわかりやすさも上がるんじゃないかなと思います～

こちらで
・consolelogの削除
だけは実施した後マージして大丈夫です！ お疲れさまでした。

2023-06-28 01:05 UTC, kawashima26 commented
@poemypoemy8 
レビューしていただき、ありがとうございます！
ぽえみーさんのレビューを受けて、自分が書いたコードがすっきりと分かりやすくなっていくのが気持ち良かったです！
合計金額をtotalだけでまとめて書けるように工夫できるところも大変勉強になりました！

console.logを削除しましたのでマージさせていただきます。ありがとうございます！

2023-06-28 01:05 UTC, merged