task05（中間課題）をアップロードしました！
kawashima26/kintone_Dojo pull request #5
Opened 2023-06-22 01:59 UTC by kawashima26

@poemypoemy8 @s-iwakawa 
お世話になっております。
中間課題をアップロードいたしました。

【ファイルの説明】
以下の2つのファイルをアップしています。
- 中間課題.html
- 中間課題_追加課題.html
  - 「余裕があれば」の課題も含めたコードです

お忙しいところ恐縮ですが、お手すきの際に何卒よろしくお願いいたします🙇‍♀️

2023-06-26 01:46 UTC, poemypoemy8 requested changes

2023-06-26 01:46 UTC, poemypoemy8 commented on task05/中間課題_追加課題.html
> +        const strTitle = titleData.slice(0, 30);
slice 以外のメソッドが適切そうです
https://www.motokis-brain.com/article/53

2023-06-26 01:49 UTC, poemypoemy8 commented
@kawashima26 
おつかれさまでした。
基本的には動作しているのが確認できたのでOKです！

今回すべてHTMLファイル内で記述してもらいましたが、
・HTMLファイル
・CSSファイル
・Javascriptファイル
に分けて記述してもらえると、後から処理を見返したときによりわかやすい記述になったかと思います。
また、その場合かなり書き方が違っていたと思います！

上記のコメント部分を修正のうえ、
再度レビュー依頼お願いします。

2023-06-26 05:56 UTC, kawashima26 commented
お世話になっております。レビューしていただきありがとうございます！

１）
> slice 以外のメソッドが適切そうです

送ってくださった参考サイトを拝見し、slice()からsubstr()に変更しました。
substr()を選んだ理由としては、
slice()の場合：第二引数は「文字列を切り出す終了位置」
substr()の場合：第二引数は「切り出す文字数」
となるため、今回の課題ではsubstr()が適切だと判断したからです。合っておりますでしょうか…？🙏

２）
> ・HTMLファイル
・CSSファイル
・Javascriptファイル
に分けて記述してもらえると、後から処理を見返したときによりわかやすい記述になったかと思います。

失礼しました…自分でも「ここはCSSの部分で…」というように考えながら書いていたので、ぽえみーさんのレビューを読んで分ければ分かりやすかったと気づきました…！

2023-06-27 23:48 UTC, poemypoemy8 approved these changes
課題お疲れさまでした！
レビューOKです🙆‍♀️

.slice と .substrメソッドについても、
「文字数」が30文字を超えた場合、となっているので
今回は `substr` メソッドが適切だと思います。

ちなみにですが、 `innerHTML` というHTMLの中身を書き換えるコードを使って、
のように入れ込んでしまうやり方とかもあったりしました🤗
（自分が去年やったとき、こんなやり方あったのか…と衝撃だったので載せておきますね）
  `
 html += <tr>
            <td>${val.day.value}</td>
            <td class="${val.label.value}">${val.category.value}</td>
            <td><a href="${val.url.value}" target="${val.target.value}">${val.content.value}</a></td>
          </tr>;
`

では、マージいただき問題ありません。
お疲れさまでした！

2023-06-28 01:16 UTC, kawashima26 commented
@poemypoemy8 
レビューしていただき、ありがとうございます！
判断をする上で「文字数」という部分が大切なのですね！

innerHTMLの書き方、私も驚いています…！！こんなに短い形ですっきりと書ける方法があるのですね！
勉強になりました。ありがとうございます！

お忙しい中、いつも分かりやすいレビューをしていただき、本当にありがとうございました！🙇‍♀️
このままマージさせていただきます。

2023-06-28 01:16 UTC, merged