task06をアップロードしました
kawashima26/kintone_Dojo pull request #6
Opened 2023-06-23 01:36 UTC by kawashima26

いつもお世話になっております。
task06の課題をアップロードしました。
お手すきの際にレビューをよろしくお願いいたします🙇‍♀️

2023-06-25 23:36 UTC, poemypoemy8 commented
@s-iwakawa 
ここからいわくんレビューでお願いします！
（devCampの準備期間と重複して時間とりづらいとかがあれば教えてください🙇‍♀️）

2023-06-26 03:09 UTC, s-iwakawa requested changes
お疲れ様です。

- 変数名
- forEachにする
- テーブルのデータ構造を記述する形で行を追加する

以上修正して、commit → プルリクお願いします。

2023-06-26 03:09 UTC, s-iwakawa commented on task06/.vscode/settings.json
このsettings.jsonのような個人の設定ファイルは .gitignore という「git管理しない対象を設定できるファイル」に .vscode を記述して、githubにはあげないようにしましょう！

2023-06-26 03:09 UTC, s-iwakawa commented on task06/task06.js
> +    }
ここはせっかく11行目で tableElement という配列を持つ変数を作っているので、for文ではなくて、forEachを使いましょう！

2023-06-26 03:09 UTC, s-iwakawa commented on task06/task06.js
> +  const ActionArr = ['あくなき探求', '不屈の心体', '理想への共感', '心を動かす', '知識を増やす', '公明正大'];
変数名はキャメルケースに従って作成しましょう。
なので、最初は小文字スタートが絶対。

ググってみて

2023-06-26 03:09 UTC, s-iwakawa commented on task06/task06.js
> +  const ActionArr = ['あくなき探求', '不屈の心体', '理想への共感', '心を動かす', '知識を増やす', '公明正大'];
11行目の変数名も同じ！

2023-06-26 03:09 UTC, s-iwakawa commented on task06/task06.js
> +      const TableClone = structuredClone(TableElement[0]); // 初期設定で存在しているテーブルの1行目をディープコピー
ディープコピーの概念を知ることはめっちゃ重要です！すごい！

structuredCloneで新しい配列を作るながれはいいんですが、
何が入っているか中身がわからない状態になっています。ブラックボックス化しているイメージですね。

kintoneカスタマイズっぽくかくとすれば
```
tblElement.push({
  value: {
    xxx:  {
      value: action5[i]
    },
    …
  }
});
```
わかりやすくすると
```
const td = {
  value: {
    xxx:  {
      value: action5[i]
    },
    …
  }
};

tblElement.push(td);
```

みたいな形で書くと、kintoneのテーブル構造もわかって良いと思います。

2023-06-27 00:10 UTC, kawashima26 commented on task06/.vscode/settings.json
承知しました！
昨夜、task07のブランチの方で、task07フォルダの中に.gitignoreファイルを作成して.vscodeを記述しました。
これでtask06とtask07の.vscodeフォルダがどちらもgit管理の対象外になっているかどうか不安なのですが、反映されておりますでしょうか…？🙇‍♀️

2023-06-27 01:29 UTC, kawashima26 commented
@s-iwakawa 
お世話になっております。レビューを受けて以下の三点を修正しました。

1. for文をforeach文に変更

2. 変数名をキャメルケースに従って変更
キャメルケースについて調べました。
先頭の要素語は小文字、先頭以外の要素語の最初を大文字で書くということを学べました。
https://www.wakuwakubank.com/posts/804-it-naming-convention/
今後の課題もキャメルケースに沿って変数名を定義したいと思います！

3. テーブルのデータ構造を中身が分かる形で行追加

お忙しいところ恐縮ですが、ご確認よろしくお願い致します。

2023-07-05 11:29 UTC, s-iwakawa approved these changes
お疲れ様です！
マージOKです！
（レビュー遅れて申し訳ないです！）

2023-07-06 02:36 UTC, kawashima26 commented
いつもお忙しい中ありがとうございます！岩川さんのご都合が良いときで構いません🙇‍♀️
マージさせていただきます！

2023-07-06 02:36 UTC, merged