task07をアップロードしました
kawashima26/kintone_Dojo pull request #7
Opened 2023-06-26 01:34 UTC by kawashima26

@poemypoemy8 @s-iwakawa 
お世話になっております。
task07の課題をアップロードしました。
お手すきの際にレビューをお願いいたします。

2023-06-26 07:57 UTC, s-iwakawa requested changes

2023-06-26 07:57 UTC, s-iwakawa commented on task07/.vscode/settings.json
task6 と同様で、.gitignore に `.vscode` を記述して git管理下から外しておいてください

2023-06-26 07:57 UTC, s-iwakawa commented on task07/task07.js
> +    console.log(event); // アプリのデータオブジェクト確認
デバッグの際には必要ですが、提出するファイルには不要です！

2023-06-26 07:57 UTC, s-iwakawa commented on task07/task07.js
文字列結合の処理を行うイベントと、disabled にするイベントは別の方が良いです！

また、create.show, edit.show まではOKなのですが、.change.<field-code>の部分がcreateだったり、editだったりするので、イベント名を見直してみてください。

抜け漏れがない理想を考える -> 例えば、新規レコードを作るときだけじゃなくて、編集画面でも値をいじることがありそうだな。-> 編集画面でも同じ操作になる必要がある
みたいな感じで、できたものをテストする前に設計してみてください！

2023-06-27 02:18 UTC, kawashima26 commented
@s-iwakawa 
お世話になっております。いつもレビューをありがとうございます。
レビューを受けて以下の点を変更しました。
1. 確認用のconsole.logを削除
2. 文字列結合の処理を行うイベントと、disabled にするイベントを分ける
3. イベント名の追加
> .change.の部分がcreateだったり、editだったりするので、イベント名を見直してみてください。
> できたものをテストする前に設計してみてください！

イベント名について、考えが足りていなかったことに気づきました！自分がどのような設計にしたいのか想像して、抜け漏れがないかどうか確認していこうと思います。

5. キャメルケースに従って変数名を変更

お忙しいところ恐縮ですが、ご確認よろしくお願い致します。

2023-06-27 05:02 UTC, s-iwakawa approved these changes
いいと思います！
マージしておkです

2023-06-27 05:10 UTC, kawashima26 commented
ありがとうございます！マージします！

2023-06-27 05:10 UTC, merged