task09をアップロードしました。
kawashima26/kintone_Dojo pull request #9
Opened 2023-06-28 04:14 UTC by kawashima26

@s-iwakawa
お世話になっております。
task09の課題をアップロードしました。
お手すきの際にご確認よろしくお願い致します。

2023-07-05 11:36 UTC, s-iwakawa requested changes
ほぼOKなのですが、一点修正をお願いします！

2023-07-05 11:36 UTC, s-iwakawa commented on task09/task09.js
> +    return kintone.api(kintone.api.url('/k/v1/records', true), 'GET', body).then((recordData) => {
このままでは、一度新規レコードを作成して、レコード編集画面で何も変えずに保存すると、他のレコードに重複がなくてもアラートが起動してしまいます。
要は、自分自身を含む全体を検索してきて、自分自身しか存在しないのに重複してますよ　という状態になっています。

レビュー遅れてて申し訳ないですが、修正お願いできますか？
ヒントとしては、複数レコードを取得する際に自分自身のレコード以外を取得することです

2023-07-07 06:11 UTC, kawashima26 commented
@s-iwakawa 

いつもお世話になっております。お疲れ様です。
修正遅くなり申し訳ありません🙇‍♀️

岩川さんのレビューを受けて「複数レコードを取得する際に自分自身のレコード以外を取得する」という部分の処理をqueryで追加しました。

- 三項演算子は、以下のサイトを参考にしました
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_operator

- kintoneAPIのクエリの書き方は以下を参考にしました。イコール先の文字列は、`文字列_0 = "テスト"`のように""でくくる必要があると学びました
https://cybozu.dev/ja/kintone/docs/overview/query/

お忙しいところ恐れ入りますが、ご確認よろしくお願いいたします🙇‍♀️

2023-07-07 09:59 UTC, s-iwakawa commented
訂正ありがとう！
ところで、このコードって動いた…？

ないものを探しに行こうとすると、エラーが出る気がする！

今回のケースだと、イベントごとに書いてしまってOK！

```
('app.record.create.submit', () => {...});

('app.record.edit.submit' () => {...});
```
みたいな感じで、クエリなし版とクエリあり版って感じ！

2023-07-10 02:55 UTC, kawashima26 commented
@s-iwakawa 
レビューありがとうございます！
失礼しました、確認が足りておらず申し訳ありません…。確認したところ、レコード新規作成時に新しいものを登録しようとするとエラーが出ておりました。

イベントごとに書く修正をしました！クエリの部分以外は同じ処理を書くことになってしまったのですが、何か良い方法はありますでしょうか…？
if文で「'app.record.create.submit'の場合～～」と「'app.record.edit.submit'の場合～」など分けて書けたりするのかと考えましたが、devnetで調べても上手くヒットしない状態です。

何度も本当に申し訳ありません。何卒アドバイスよろしくお願い致します。

2023-07-10 05:20 UTC, s-iwakawa approved these changes

2023-07-11 01:21 UTC, merged